const C=window.CATALOGS,CFG=window.APP_CONFIG||{};let items=[],selectedSupplier=null,selectedPC=null,selectedProduct=null,currentGroup=null,currentOrderToken=null,previewGroup=null;
const $=id=>document.getElementById(id);const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const money=(n,c)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:c==='US DOLLAR'?'USD':c==='NUEVO SOL'?'PEN':'EUR'}).format(n||0);
const remote=!!(CFG.SUPABASE_URL&&CFG.SUPABASE_ANON_KEY&&window.supabase);const db=remote?window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_ANON_KEY):null;
function options(id,data,blank='Seleccionar…',map=x=>({v:x,t:x})){const el=$(id);el.innerHTML=`<option value="">${blank}</option>`+data.map(x=>{let m=map(x);return `<option value="${esc(m.v)}">${esc(m.t)}</option>`}).join('')}
options('buyer',C.buyers);options('currency',C.currencies);options('openPO',C.openOptions,'Seleccionar…');options('local',C.locals,'Seleccionar…',x=>({v:x.id,t:`${x.id} · ${x.name}`}));options('emergency',C.emergencyTypes,'Ninguna',x=>({v:x==='Ninguna'?'':x,t:x}));
function combo(inputId,menuId,data,label,sub,onPick){const input=$(inputId),menu=$(menuId);function draw(){let q=input.value.toLowerCase().trim(),rows=data.filter(x=>(label(x)+' '+sub(x)).toLowerCase().includes(q)).slice(0,30);menu.innerHTML=rows.map((x,i)=>`<div class="combo-option" data-i="${i}"><b>${esc(label(x))}</b><span>${esc(sub(x))}</span></div>`).join('')||'<div class="combo-option"><span>Sin resultados</span></div>';menu.classList.add('open');[...menu.querySelectorAll('[data-i]')].forEach(el=>el.onclick=()=>{let x=rows[+el.dataset.i];input.value=label(x);menu.classList.remove('open');onPick(x)})}input.addEventListener('input',()=>{onPick(null);draw()});input.addEventListener('focus',draw);document.addEventListener('click',e=>{if(!menu.parentElement.contains(e.target))menu.classList.remove('open')})}
combo('supplierSearch','supplierMenu',C.suppliers,x=>`${x.id} · ${x.name}`,x=>x.name,x=>selectedSupplier=x);combo('pcSearch','pcMenu',C.pcs,x=>`${x.alias} · ${x.description}`,x=>x.code,x=>selectedPC=x);combo('productSearch','productMenu',C.products,x=>`${x.code} · ${x.concept}`,x=>x.concept,x=>{selectedProduct=x;if(x)$('description').value=x.concept;else $('description').value=''});
$('productDropdownBtn').onclick=e=>{e.preventDefault();e.stopPropagation();$('productSearch').focus();$('productSearch').dispatchEvent(new Event('focus'));};
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2500)}
function nextGroupFromItems(){return items.reduce((m,x)=>Math.max(m,Number(x.group)||0),0)+1}
async function refreshGroupPreview(){
  if(currentGroup){$('group').value=currentGroup;$('group').previousElementSibling && 0;return currentGroup}
  let n=nextGroupFromItems();
  if(remote){const {data,error}=await db.rpc('peek_next_po_group');if(!error&&data!=null)n=Number(data)}
  previewGroup=n;$('group').value=n;
  const help=$('group').parentElement.querySelector('.field-help');if(help)help.textContent='Grupo previsto. Se confirma al agregar el primer ítem.';
  return n
}
function newOrderToken(){return (crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`)}
const headerIds=['seller','buyer','supplierSearch','currency','openPO','local','emergency','note'];
function setOrderLocked(locked){
  headerIds.forEach(id=>{const el=$(id);if(el)el.disabled=locked});
  const card=$('group').closest('.card');if(card)card.classList.toggle('order-locked',locked);
  $('activeOrderPanel').classList.toggle('hidden',!locked);
  $('newOrderBtn').textContent=locked?'✓ Finalizar orden':'＋ Nueva orden';
  if(locked){const own=items.filter(x=>x.orderToken===currentOrderToken||Number(x.group)===Number(currentGroup));$('activeOrderTitle').textContent=`Grupo ${currentGroup} · ${own.length} ítem${own.length===1?'':'s'}`;$('activeOrderMeta').textContent='Los nuevos productos se agregarán a este mismo grupo y conservarán la moneda de la orden. El Alias / PC se elige en cada línea.'}
}
function clearHeader(){['seller','supplierSearch','pcSearch','note'].forEach(id=>$(id).value='');['buyer','currency','openPO','local','emergency'].forEach(id=>$(id).value='');selectedSupplier=selectedPC=null}
async function finishCurrentOrder(showToast=true){if(!currentGroup)return prepareNewOrder(showToast);currentGroup=null;currentOrderToken=newOrderToken();setOrderLocked(false);clearHeader();const n=await refreshGroupPreview();if(showToast)toast(`Orden finalizada · Grupo previsto ${n}`)}
async function prepareNewOrder(showToast=true){currentGroup=null;currentOrderToken=newOrderToken();setOrderLocked(false);clearHeader();const n=await refreshGroupPreview();if(showToast)toast(`Nueva orden preparada · Grupo previsto ${n}`)}
$('newOrderBtn').onclick=()=>currentGroup?finishCurrentOrder(true):prepareNewOrder(true);$('finishOrderBtn').onclick=()=>finishCurrentOrder(true);
function normalizeRemote(x){return {id:x.id,group:Number(x.group_no),seller:x.seller,buyer:x.buyer,supplierId:x.supplier_id,supplierName:x.supplier_name,currency:x.currency,productId:x.product_id,description:x.description,qty:Number(x.qty),cost:Number(x.cost),total:Number(x.total),local:x.local_id,alias:x.alias,note:x.note||'',open:x.open_po||'',emergency:x.emergency||'',pcCode:x.pc_code||'',orderToken:x.order_token||''}}
async function loadItems(){if(remote){const {data,error}=await db.from('po_items').select('*').order('id');if(error){toast('No se pudo sincronizar la bandeja compartida.');return}items=(data||[]).map(normalizeRemote)}else items=JSON.parse(localStorage.getItem('po_items')||'[]');render();if(!currentGroup)showNextGroup()}
function persistLocal(){if(!remote)localStorage.setItem('po_items',JSON.stringify(items))}
$('addItem').onclick=async()=>{let qty=+$('qty').value,cost=+$('unitCost').value,seller=$('seller').value.trim();if(!seller||!$('buyer').value||!selectedSupplier||!$('currency').value||!$('local').value||!selectedPC||!selectedProduct||!$('description').value.trim()||qty<=0||cost<0){toast('Completa los campos obligatorios, incluido el vendedor.');return}try{
let base={seller,buyer:$('buyer').value,supplierId:selectedSupplier.id,supplierName:selectedSupplier.name,currency:$('currency').value,productId:selectedProduct.code,description:$('description').value.trim(),qty,cost,total:qty*cost,local:$('local').value,alias:selectedPC.alias,note:$('note').value.trim(),open:$('openPO').value,emergency:$('emergency').value,pcCode:selectedPC.code};
if(remote){if(!currentOrderToken)currentOrderToken=newOrderToken();const payload={p_order_token:currentOrderToken,p_seller:base.seller,p_buyer:base.buyer,p_supplier_id:String(base.supplierId),p_supplier_name:base.supplierName,p_currency:base.currency,p_product_id:base.productId,p_description:base.description,p_qty:base.qty,p_cost:base.cost,p_total:base.total,p_local_id:base.local,p_alias:base.alias,p_note:base.note,p_open_po:base.open,p_emergency:base.emergency,p_pc_code:base.pcCode};const before=previewGroup;const {data,error}=await db.rpc('add_po_item_atomic',payload);if(error)throw error;currentGroup=Number(data);$('group').value=currentGroup;const help=$('group').parentElement.querySelector('.field-help');if(help)help.textContent='Grupo asignado a esta orden.';await loadItems();if(before&&Number(before)!==currentGroup)toast(`El grupo ${before} fue ocupado antes. Tu orden recibió automáticamente el grupo ${currentGroup}.`);else toast(`Ítem agregado · Grupo ${currentGroup} confirmado.`)}else{if(!currentGroup)currentGroup=nextGroupFromItems();let x={...base,group:currentGroup,orderToken:currentOrderToken||newOrderToken()};items.push(x);persistLocal();render();$('group').value=currentGroup;toast(`Ítem agregado · Grupo ${currentGroup} confirmado.`)}
setOrderLocked(true);$('productSearch').value='';$('description').value='';$('pcSearch').value='';$('qty').value=1;$('unitCost').value='';selectedProduct=null;selectedPC=null}catch(e){console.error(e);toast('No se pudo agregar el ítem. Revisa la configuración compartida.')}};
function render(){if(currentGroup)setOrderLocked(true);const b=$('itemsBody');b.innerHTML=items.map((x,i)=>`<tr><td><b>${x.group}</b></td><td>${esc(x.seller||'—')}</td><td>${esc(x.buyer)}</td><td><b>${esc(x.supplierName)}</b><br><span class="muted">${esc(x.supplierId)}</span></td><td><b>${esc(x.productId)}</b></td><td class="desc-cell">${esc(x.description)}</td><td>${esc(x.currency)}</td><td><b>${esc(x.alias)}</b><br><span class="muted">${esc(x.pcCode)}</span></td><td class="num">${x.qty}</td><td class="num">${money(x.cost,x.currency)}</td><td class="num"><b>${money(x.total,x.currency)}</b></td><td><button class="delete" onclick="removeItem(${i})">✕</button></td></tr>`).join('');$('emptyState').classList.toggle('hidden',items.length>0);let groups=new Set(items.map(x=>x.group)).size;$('tableSubtitle').textContent=items.length?`${items.length} línea${items.length>1?'s':''} en ${groups} orden${groups!==1?'es':''}${remote?' · bandeja compartida':''}.`:'Aún no hay líneas agregadas.';$('metricGroups').textContent=groups;$('metricItems').textContent=items.length;$('metricUsd').textContent=money(items.filter(x=>x.currency==='US DOLLAR').reduce((a,b)=>a+b.total,0),'US DOLLAR');$('metricPen').textContent=money(items.filter(x=>x.currency==='NUEVO SOL').reduce((a,b)=>a+b.total,0),'NUEVO SOL')}
window.removeItem=async i=>{let x=items[i];if(remote){const {error}=await db.from('po_items').delete().eq('id',x.id);if(error)return toast('No se pudo eliminar.');await loadItems();if(!items.length){await db.rpc('reset_po_group_if_empty');currentGroup=null;await prepareNewOrder(false)}else if(currentGroup===Number(x.group)&&!items.some(r=>Number(r.group)===currentGroup)){currentGroup=null;await prepareNewOrder(false)}else await refreshGroupPreview()}else{items.splice(i,1);persistLocal();render();if(!items.length){currentGroup=null;await prepareNewOrder(false)}}toast('Línea eliminada.');};
$('clearBtn').onclick=async()=>{if(!items.length||!confirm('¿Eliminar todas las líneas preparadas?'))return;if(remote){const ids=items.map(x=>x.id);const {error}=await db.from('po_items').delete().in('id',ids);if(error)return toast('No se pudo limpiar la bandeja.');await loadItems();await db.rpc('reset_po_group_if_empty')}else{items=[];persistLocal();render()}currentGroup=null;await prepareNewOrder(false);toast('Bandeja limpia. El siguiente grupo vuelve a ser 1.');};$('saveBtn').onclick=()=>toast(remote?'Los cambios ya están guardados en la bandeja compartida.':'Borrador guardado en este navegador.');
function exportRows(snapshot){let map=new Map(),next=1;return snapshot.map(x=>{if(!map.has(x.group))map.set(x.group,next++);return {'Grupo':map.get(x.group),'Vendedor':x.seller||'','Id Comprador':x.buyer,'Id Proveedor':Number(x.supplierId)||x.supplierId,'Nombre Proveedor':x.supplierName,'Id Moneda':x.currency,'Id Producto':x.productId,'Descripcion Producto':x.description,'Cantidad':x.qty,'Costo Unitario':x.cost,'Costo Total':x.total,'Id Local':x.local,'Alias':x.alias,'Nota':x.note||'','OC Abierta':x.open||'','TipoEmergencia':x.emergency||''}})}
$('exportBtn').onclick=async()=>{if(!items.length)return toast('No hay órdenes para exportar.');let snapshot=[...items],rows=exportRows(snapshot);if(!confirm(`Se exportarán ${snapshot.length} líneas. Los grupos del Excel se renumerarán desde 1 y, al finalizar, esas líneas se retirarán de la bandeja. ¿Continuar?`))return;try{if(window.XLSX){const headers=['Grupo','Vendedor','Id Comprador','Id Proveedor','Nombre Proveedor','Id Moneda','Id Producto','Descripcion Producto','Cantidad','Costo Unitario','Costo Total','Id Local','Alias','Nota','OC Abierta','TipoEmergencia'];const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows,{header:headers});ws['!cols']=[8,24,20,15,28,14,14,50,10,14,14,12,12,24,12,18].map(w=>({wch:w}));XLSX.utils.book_append_sheet(wb,ws,'Datos');XLSX.writeFile(wb,`Ordenes_Compra_${new Date().toISOString().slice(0,10)}.xlsx`)}else throw new Error('XLSX no disponible');if(remote){const ids=snapshot.map(x=>x.id);const {error}=await db.from('po_items').delete().in('id',ids);if(error)throw error;await loadItems();const {error:resetError}=await db.rpc('reset_po_group_if_empty');if(resetError)console.warn('No se reinició la secuencia:',resetError)}else{items=items.filter(x=>!snapshot.includes(x));persistLocal();render();}await prepareNewOrder(false);toast('Excel descargado. Bandeja limpia y numeración preparada para el siguiente lote.')}catch(e){console.error(e);toast('El Excel se generó, pero no se pudo completar la limpieza. Revisa la bandeja.')}};
[...document.querySelectorAll('.nav-item')].forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));n.classList.add('active');let cat=n.dataset.view==='catalog';$('editorView').classList.toggle('active',!cat);$('catalogView').classList.toggle('active',cat);$('pageTitle').textContent=cat?'Catálogos':'Nueva carga';if(cat)renderCatalog()});$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('po_dark',document.body.classList.contains('dark'))};if(localStorage.getItem('po_dark')==='true')document.body.classList.add('dark');
let activeTab='products';document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');activeTab=t.dataset.tab;renderCatalog()});$('catalogSearch').oninput=renderCatalog;$('prodCount').textContent=C.products.length;$('pcCount').textContent=C.pcs.length;$('buyerCount').textContent=C.buyers.length;$('localCount').textContent=C.locals.length;
function renderCatalog(){let q=$('catalogSearch').value.toLowerCase(),rows=[],head=[];if(activeTab==='products'){head=['Código','Concepto',''];rows=C.products.map(x=>[x.code,x.concept,''])}if(activeTab==='pcs'){head=['Alias','Descripción','PC Code / Analítica'];rows=C.pcs.map(x=>[x.alias,x.description,x.code])}if(activeTab==='buyers'){head=['ID comprador','',''];rows=C.buyers.map(x=>[x,'',''])}if(activeTab==='locals'){head=['ID local','Nombre','',''];rows=C.locals.map(x=>[x.id,x.name,''])}rows=rows.filter(r=>r.join(' ').toLowerCase().includes(q));$('catalogTable').innerHTML=`<div class="catalog-row header">${head.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`+rows.map(r=>`<div class="catalog-row">${r.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`).join('')}
if(!remote){$('tableSubtitle').title='Modo local: configura Supabase para compartir la bandeja entre usuarios.'}(async()=>{await loadItems();await prepareNewOrder(false);if(remote){db.channel('po-items-live').on('postgres_changes',{event:'*',schema:'public',table:'po_items'},async()=>{await loadItems();if(!currentGroup)await refreshGroupPreview()}).subscribe();setInterval(async()=>{await loadItems();if(!currentGroup)await refreshGroupPreview()},30000)}})();

// v10.1: estado visual accesible del desplegable de Producto
(function(){
  const btn=document.getElementById('productDropdownBtn');
  const menu=document.getElementById('productMenu');
  if(!btn||!menu)return;
  const sync=()=>btn.setAttribute('aria-expanded', menu.classList.contains('open')?'true':'false');
  btn.setAttribute('aria-expanded','false');
  btn.addEventListener('click',()=>setTimeout(sync,0));
  document.addEventListener('click',()=>setTimeout(sync,0));
  const obs=new MutationObserver(sync);
  obs.observe(menu,{attributes:true,attributeFilter:['class']});
})();
